apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hwameistor
  namespace: {{ .Values.global.targetNamespace }}
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: metrics
  namespaceSelector:
    matchNames:
    - hwameistor
  selector:
    matchLabels:
      app: hwameistor-exporter
